version: '3'
services:
  node:
    container_name: 'sample-nextjs'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    tty: true
    volumes:
      - './:/nextjs/'
